In [1]:
import cvxpy as cp
import numpy as np

(CVXPY) May 18 12:25:57 AM: Encountered unexpected exception importing solver GLOP:
RuntimeError('Unrecognized new version of ortools (9.11.4210). Expected < 9.10.0. Please open a feature request on cvxpy to enable support for this version.')
(CVXPY) May 18 12:25:57 AM: Encountered unexpected exception importing solver PDLP:
RuntimeError('Unrecognized new version of ortools (9.11.4210). Expected < 9.10.0. Please open a feature request on cvxpy to enable support for this version.')


In [2]:
scale = np.array([10000, 1000, 100, 10, 1])
B1 = np.array([1, 2, 3, 4, 5])
B2 = np.array([6, 7, 8, 9, 10])

X = cp.Variable((5, 5), integer=True)
K1 = cp.Variable(5, integer=True)
K2 = cp.Variable(5, integer=True)
constraints = [X >= 0, 
               X <= 9,
               K1 >= 1,
               K1 <= 99999,
               K2 >= 1,
               K2 <= 22222,
               X[0, 0] == 9,
               X[4, 4] == 0,
               X @ scale == cp.multiply(K1, B1),
               X.T @ scale == cp.multiply(K2, B2) ]


In [3]:
objective = cp.Maximize(cp.sum(X))
problem = cp.Problem(objective, constraints)
problem.solve()

np.float64(205.0)

In [4]:
print(X.value, K1.value, K2.value)

[[9. 8. 9. 9. 9.]
 [9. 9. 9. 9. 8.]
 [7. 9. 8. 9. 9.]
 [9. 9. 8. 9. 6.]
 [8. 9. 8. 9. 0.]] [98999. 49999. 26633. 24974. 17978.] [16633. 12857. 12486. 11111.  9896.]
